name: "Terraform snyk testing for acr"


trigger:
  branches:
    include:
      - main
pr:
  branches:
    include:
      - '*'
      
pool:
  vmImage: ubuntu-latest
  
resources:
  repositories:
    - repository: Snyk
      type: github
      name: duck-creek/ADO.Pipelines.Templates
      ref: 335407-Snyk
      endpoint: 'Duck Creek'  
  
steps:
- checkout: self
  displayName: Clean Checkout
  clean: true
  

- task: AzureKeyVault@2
  displayName: Get common secrets from Master KV
  inputs:
       azureSubscription: "dcodnext-provisioning"
       KeyVaultName: "ueprovkv"
       # TODO: Change Key Vault Variable Names to be consitent, decide on a naming convention for Key Vault Secrets, and use everywhere.
       SecretsFilter: "dcodnext-snyk-token"
       RunAsPreJob: false

- template: frameWork/common/snyk/main.yml@Snyk
  parameters:
    testType: 'iac'
    snykToken: '$(dcodnext-snyk-token)'
    moduleLocation: './module'
